dist: xenial
language: python
sudo: false
cache:
  directories:
    - ~/arduino_ide

git:
  depth: false
  quiet: true

python:
  - "3.8"

before_install:
  - source $TRAVIS_BUILD_DIR/install.sh

script:
  - build_platform nrf52840
  - build_platform esp32
  - build_platform uno
  - build_platform leonardo
  - build_platform zero
  - build_platform esp8266
  - build_platform m4

notifications:
  email:
    on_success: change
    on_failure: change
